[project]
name = "tileto370"
version = "1.0.0"
description = "Tile conversion from NetHack 3.6.x to 3.7.0 beta."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow>=12.1.1",
]
license = "MIT"
license-files = ["LICENSE.txt"]


[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "TD", # TODOs format
]
